# Generated by Django 5.0.7 on 2024-07-18 23:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.BigIntegerField()),
                ('message', models.TextField()),
                ('isRead', models.BooleanField(default=False)),
                ('sentDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.BigIntegerField()),
                ('ticketID', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('reservationDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusID', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketID', models.AutoField(primary_key=True, serialize=False)),
                ('eventID', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalAvailable', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfUser',
            fields=[
                ('typeId', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('organizerId', models.BigIntegerField()),
                ('url', models.CharField(default='', max_length=255)),
                ('categoryEvent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EventraApp.categoryevent')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('refundID', models.AutoField(primary_key=True, serialize=False)),
                ('paymentID', models.BigIntegerField()),
                ('refundAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refundDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('refundStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventraApp.status')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentID', models.AutoField(primary_key=True, serialize=False)),
                ('reservationID', models.BigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentMethod', models.CharField(max_length=50)),
                ('paymentDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('paymentStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventraApp.status')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('typeOfUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventraApp.typeofuser')),
            ],
        ),
    ]
